<a href="https://colab.research.google.com/github/Riyaz127/TNS-Practice/blob/main/Batch2_day10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from google.colab import files

uploaded=files.upload()

Saving student.csv to student.csv

In [2]:
df=pd.read_csv("student.csv")
print(df)

     Name  Age  Marks Department   Exam_date
0   Riyaz   21     85        CSE  2026-06-10
1  Ayesha   20     92        ECE  2026-06-11
2   Rahul   22     78       MECH  2026-06-12
3   Sneha   21     88        EEE  2026-06-13
4   Arjun   20     95        CSE  2026-06-14
5   Priya   22     81        ECE  2026-06-15
6   Kiran   21     76      CIVIL  2026-06-16
7   Meena   20     89        CSE  2026-06-17
8  Vikram   23     73       MECH  2026-06-18
9  Anjali   21     91        EEE  2026-06-19

In [3]:
#Filtering students who scored marks > 80
print(df[df['Marks']>80])

     Name  Age  Marks Department   Exam_date
0   Riyaz   21     85        CSE  2026-06-10
1  Ayesha   20     92        ECE  2026-06-11
3   Sneha   21     88        EEE  2026-06-13
4   Arjun   20     95        CSE  2026-06-14
5   Priya   22     81        ECE  2026-06-15
7   Meena   20     89        CSE  2026-06-17
9  Anjali   21     91        EEE  2026-06-19

In [4]:
# Sorting sort the df based on marks in descending
df.sort_values(by="Marks",ascending=False)

     Name  Age  Marks Department   Exam_date
4   Arjun   20     95        CSE  2026-06-14
1  Ayesha   20     92        ECE  2026-06-11
9  Anjali   21     91        EEE  2026-06-19
7   Meena   20     89        CSE  2026-06-17
3   Sneha   21     88        EEE  2026-06-13
0   Riyaz   21     85        CSE  2026-06-10
5   Priya   22     81        ECE  2026-06-15
2   Rahul   22     78       MECH  2026-06-12
6   Kiran   21     76      CIVIL  2026-06-16
8  Vikram   23     73       MECH  2026-06-18

In [5]:
#Adding Columns
def asign_grade(score):
  if score >=90:
    return "A"
  elif score>=80 and score<90:
    return "B"
  elif score>=70 and score<80:
    return "C"
  else:
    return "D"
df["Grade"]=df["Marks"].apply(asign_grade)
print(df)

     Name  Age  Marks Department   Exam_date Grade
0   Riyaz   21     85        CSE  2026-06-10     B
1  Ayesha   20     92        ECE  2026-06-11     A
2   Rahul   22     78       MECH  2026-06-12     C
3   Sneha   21     88        EEE  2026-06-13     B
4   Arjun   20     95        CSE  2026-06-14     A
5   Priya   22     81        ECE  2026-06-15     B
6   Kiran   21     76      CIVIL  2026-06-16     C
7   Meena   20     89        CSE  2026-06-17     B
8  Vikram   23     73       MECH  2026-06-18     C
9  Anjali   21     91        EEE  2026-06-19     A

In [14]:
#modifying column
# convert all the names of the students into upper case letters
upper_case=df["Name"].str.upper()
print(upper_case)

0     RIYAZ
1    AYESHA
2     RAHUL
3     SNEHA
4     ARJUN
5     PRIYA
6     KIRAN
7     MEENA
8    VIKRAM
9    ANJALI
Name: Name, dtype: object

In [23]:
#Removing columns
#remove department column from dataframe
df.drop(columns='Department')

     Name  Age  Marks   Exam_date Grade
0   Riyaz   21     85  2026-06-10     B
1  Ayesha   20     92  2026-06-11     A
2   Rahul   22     78  2026-06-12     C
3   Sneha   21     88  2026-06-13     B
4   Arjun   20     95  2026-06-14     A
5   Priya   22     81  2026-06-15     B
6   Kiran   21     76  2026-06-16     C
7   Meena   20     89  2026-06-17     B
8  Vikram   23     73  2026-06-18     C
9  Anjali   21     91  2026-06-19     A

In [24]:
#Dropping rows
#remove the student records index 3
df.drop(index=3)

     Name  Age  Marks Department   Exam_date Grade
0   Riyaz   21     85        CSE  2026-06-10     B
1  Ayesha   20     92        ECE  2026-06-11     A
2   Rahul   22     78       MECH  2026-06-12     C
4   Arjun   20     95        CSE  2026-06-14     A
5   Priya   22     81        ECE  2026-06-15     B
6   Kiran   21     76      CIVIL  2026-06-16     C
7   Meena   20     89        CSE  2026-06-17     B
8  Vikram   23     73       MECH  2026-06-18     C
9  Anjali   21     91        EEE  2026-06-19     A

In [32]:
#Groupby
#find the average marks in each department
df.groupby("Department")["Marks"].mean().round(2)

Department
CIVIL    76.00
CSE      89.67
ECE      86.50
EEE      89.50
MECH     75.50
Name: Marks, dtype: float64

In [49]:
#Aggregate Function
#calculate the mean,max,min,sum,median,std.(statistics)
statistic=df["Marks"].agg(["mean","max","min","sum","median","std"])
print(statistic)
# stat=df.groupby("Department")["Marks"].agg(["mean","max","min","sum","median","std"])
# print(stat)

mean       84.800000
max        95.000000
min        73.000000
sum       848.000000
median     86.500000
std         7.450578
Name: Marks, dtype: float64

In [59]:
#Combining DataFrame
#create an another dataframe and add both the dataframe
new={
    "Name":["Teja","Divya"],
    "Age":[20,21],
    "Marks":[87,91],
    "Department":["CSE","ECE"],
    "Exam_date":['2026-06-20','2026-06-21']
}
df1=pd.DataFrame(new)
df1["Grade"]=df1["Marks"].apply(asign_grade)
# print(df1)
#Contatination
data=pd.concat([df,df1])
print(data)

     Name  Age  Marks Department   Exam_date Grade
0   Riyaz   21     85        CSE  2026-06-10     B
1  Ayesha   20     92        ECE  2026-06-11     A
2   Rahul   22     78       MECH  2026-06-12     C
3   Sneha   21     88        EEE  2026-06-13     B
4   Arjun   20     95        CSE  2026-06-14     A
5   Priya   22     81        ECE  2026-06-15     B
6   Kiran   21     76      CIVIL  2026-06-16     C
7   Meena   20     89        CSE  2026-06-17     B
8  Vikram   23     73       MECH  2026-06-18     C
9  Anjali   21     91        EEE  2026-06-19     A
0    Teja   20     87        CSE  2026-06-20     B
1   Divya   21     91        ECE  2026-06-21     A

In [71]:
from datetime import date
#Working with data
# convert exam_date format and extract the day,month,year
date_time=pd.to_datetime(df["Exam_date"])
yr=pd.to_datetime(df["Exam_date"]).dt.year
mn=pd.to_datetime(df["Exam_date"]).dt.month
dy=pd.to_datetime(df["Exam_date"]).dt.day
print(date_time)
print("year\n",yr)
print("Month\n",mn)
print("Day\n",dy)

0   2026-06-10
1   2026-06-11
2   2026-06-12
3   2026-06-13
4   2026-06-14
5   2026-06-15
6   2026-06-16
7   2026-06-17
8   2026-06-18
9   2026-06-19
Name: Exam_date, dtype: datetime64[ns]
year
 0    2026
1    2026
2    2026
3    2026
4    2026
5    2026
6    2026
7    2026
8    2026
9    2026
Name: Exam_date, dtype: int32
Month
 0    6
1    6
2    6
3    6
4    6
5    6
6    6
7    6
8    6
9    6
Name: Exam_date, dtype: int32
Day
 0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
Name: Exam_date, dtype: int32

In [73]:
# Indexing
# set the name column as the index and display the details of the student "Rahul"
print(df[df['Name']=="Rahul"])

    Name  Age  Marks Department   Exam_date Grade
2  Rahul   22     78       MECH  2026-06-12     C

In [74]:
#Pivot Table
#Create a pivot table showing the average marks for each department
pd.pivot_table(
    data=df,
    index="Department",
    values="Marks",
    aggfunc=("mean","sum")
)

                 mean  sum
Department
CIVIL       76.000000   76
CSE         89.666667  269
ECE         86.500000  173
EEE         89.500000  179
MECH        75.500000  151