<a href="https://colab.research.google.com/github/Riyaz127/TNS-Practice/blob/main/Day17_Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

WHAT IS FEATURE ENGINEERING?


Feature Engineering is the process of transforming raw data into useful features that help machine learning moidels perform better.


In simple terms: We convert data into a form that machines can understand easily.

🔹 Why is Feature Engineering Important?


Improves model accuracy

Helps in better data understanding

Removes noise and unnecessary information

Makes patterns more visible

🔹 Types of Features

1. Numerical Features

Continuous values

Example: Age, Salary, Temperature

2. Categorical Features

Labels or categories

Example: Gender, City, Color

3. Text Features

Words or sentences

Example: Reviews, Comments

4. Date-Time Features

Time-based data

Example: Date, Timestamp

🎯 Goal of Feature Engineering


Convert raw data ➡️ meaningful inputs for ML models

In [2]:
import pandas as pd

# Sample dataset
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "Gender": ["Female", "Male", "Male"],
    "Salary": [50000, 60000, 70000],
    "Joining_Date": ["2022-01-01", "2021-06-15", "2020-03-20"]
}
df=pd.DataFrame(data)
df

      Name  Age  Gender  Salary Joining_Date
0    Alice   25  Female   50000   2022-01-01
1      Bob   30    Male   60000   2021-06-15
2  Charlie   35    Male   70000   2020-03-20

In [7]:
df.dtypes

Name            object
Age              int64
Gender          object
Salary           int64
Joining_Date    object
dtype: object

# 📌 Handling Numerical Data

## 🔹 What is Numerical Data?
Numerical data consists of numbers and can be measured.

👉 Examples:
- Age
- Salary
- Temperature

---

## 🔹 Why do we need to process numerical data?
- Different features may have different scales
- Large values can dominate smaller ones
- Models perform better when data is properly scaled

---

## 🔹 1. Feature Scaling

### 📌 Standardization
- Converts data to mean = 0 and standard deviation = 1

### 📌 Normalization (Min-Max Scaling)
- Scales values between 0 and 1

---

## 🔹 2. Log Transformation
- Used to reduce skewness in data
- Helps in handling large values

---

## 🔹 3. Binning (Discretization)
- Converts continuous values into categories
- Example: Age → Young, Adult, Old

In [8]:
import pandas as pd
import numpy as np

data={
    "Age":[18,25,30,45,60],
    "Salary":[20000,30000,50000,80000,150000]
}
df=pd.DataFrame(data)
df

   Age  Salary
0   18   20000
1   25   30000
2   30   50000
3   45   80000
4   60  150000

Feature Scaling- Standardization

In [10]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

df_scaled=df.copy()
df_scaled[["Age","Salary"]]=scaler.fit_transform(df[["Age","Salary"]])

df_scaled

        Age    Salary
0 -1.167023 -0.984309
1 -0.702866 -0.770329
2 -0.371325 -0.342368
3  0.623296  0.299572
4  1.617918  1.797434

Feature Scaling -Normalisation (Min-Max)

In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

df_normalized=df.copy()
df_normalized[["Age","Salary"]]=scaler.fit_transform(df[["Age","Salary"]])

df_normalized

        Age    Salary
0  0.000000  0.000000
1  0.166667  0.076923
2  0.285714  0.230769
3  0.642857  0.461538
4  1.000000  1.000000

Log Transformation

In [12]:
#Apply Log Transformation
df_log=df.copy()
df_log["Salary_log"]=np.log(df_log["Salary"])

df_log

   Age  Salary  Salary_log
0   18   20000    9.903488
1   25   30000   10.308953
2   30   50000   10.819778
3   45   80000   11.289782
4   60  150000   11.918391

Binning (Discretization)

In [13]:
#Create bins for Age
bins=[0,20,40,100]
labels=["Young","Adult","Senior"]

df["Age_Group"]=pd.cut(df["Age"],bins=bins,labels=labels)

df

   Age  Salary Age_Group
0   18   20000     Young
1   25   30000     Adult
2   30   50000     Adult
3   45   80000    Senior
4   60  150000    Senior