<a href="https://colab.research.google.com/github/Riyaz127/TNS-Practice/blob/main/Pandas_Exercise0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Clean Employee Data:
create employee dataset with empid,name,salary,years of experience,department with duplicate values,null values.

In [1]:
import numpy as np
import pandas as pd
from google.colab import files

uploaded=files.upload()

Saving employee_dataset.csv to employee_dataset.csv

In [24]:
df=pd.read_csv("employee_dataset.csv")
print(df)

    EmpID    Name   Salary       City  Years_of_Experience Department
0     101   Rahul  50000.0  Hyderabad                  3.0         IT
1     102   Priya  60000.0  Bangalore                  5.0         HR
2     103    Amit  55000.0    Chennai                  4.0    Finance
3     104   Sneha  70000.0     Mumbai                  7.0         IT
4     105   Kiran      NaN  Hyderabad                  2.0  Marketing
5     106  Anjali  65000.0        NaN                  6.0         HR
6     107  Vikram  80000.0       Pune                  NaN    Finance
7     108    Neha  72000.0      Delhi                  8.0        NaN
8     109   Rahul  50000.0  Hyderabad                  3.0         IT
9     110   Arjun  58000.0    Chennai                  4.0    Finance
10    111   Pooja  62000.0  Bangalore                  5.0         HR
11    112   Kiran      NaN  Hyderabad                  2.0  Marketing
12    113   Manoj  75000.0     Mumbai                  9.0         IT
13    114   Divya  68000.0       Pune                  6.0  Marketing
14    115    Neha  72000.0      Delhi                  8.0        NaN

In [25]:
#Find the missing values in each column
df.isnull().sum()

EmpID                  0
Name                   0
Salary                 2
City                   1
Years_of_Experience    1
Department             2
dtype: int64

In [4]:
# Replace missing names with unknown.
df["Name"].isnull().sum()

np.int64(0)

In [26]:
# Fill Missing Departments with the most frequent department.
df["Department"].fillna(df["Department"].mode()[0], inplace=True)
print(df)

    EmpID    Name   Salary       City  Years_of_Experience Department
0     101   Rahul  50000.0  Hyderabad                  3.0         IT
1     102   Priya  60000.0  Bangalore                  5.0         HR
2     103    Amit  55000.0    Chennai                  4.0    Finance
3     104   Sneha  70000.0     Mumbai                  7.0         IT
4     105   Kiran      NaN  Hyderabad                  2.0  Marketing
5     106  Anjali  65000.0        NaN                  6.0         HR
6     107  Vikram  80000.0       Pune                  NaN    Finance
7     108    Neha  72000.0      Delhi                  8.0         IT
8     109   Rahul  50000.0  Hyderabad                  3.0         IT
9     110   Arjun  58000.0    Chennai                  4.0    Finance
10    111   Pooja  62000.0  Bangalore                  5.0         HR
11    112   Kiran      NaN  Hyderabad                  2.0  Marketing
12    113   Manoj  75000.0     Mumbai                  9.0         IT
13    114   Divya  68000.0       Pune                  6.0  Marketing
14    115    Neha  72000.0      Delhi                  8.0         IT

/tmp/ipykernel_1777/2959351080.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Department"].fillna(df["Department"].mode()[0], inplace=True)

In [27]:
#replace missing salaries with the median salary
df['Salary'].fillna(df["Salary"].median(),inplace=True)
print(df)

    EmpID    Name   Salary       City  Years_of_Experience Department
0     101   Rahul  50000.0  Hyderabad                  3.0         IT
1     102   Priya  60000.0  Bangalore                  5.0         HR
2     103    Amit  55000.0    Chennai                  4.0    Finance
3     104   Sneha  70000.0     Mumbai                  7.0         IT
4     105   Kiran  65000.0  Hyderabad                  2.0  Marketing
5     106  Anjali  65000.0        NaN                  6.0         HR
6     107  Vikram  80000.0       Pune                  NaN    Finance
7     108    Neha  72000.0      Delhi                  8.0         IT
8     109   Rahul  50000.0  Hyderabad                  3.0         IT
9     110   Arjun  58000.0    Chennai                  4.0    Finance
10    111   Pooja  62000.0  Bangalore                  5.0         HR
11    112   Kiran  65000.0  Hyderabad                  2.0  Marketing
12    113   Manoj  75000.0     Mumbai                  9.0         IT
13    114   Divya  68000.0       Pune                  6.0  Marketing
14    115    Neha  72000.0      Delhi                  8.0         IT

/tmp/ipykernel_1777/3948558310.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df["Salary"].median(),inplace=True)

In [28]:
#Replace misssing experience with the average experience
df.fillna(df['Years_of_Experience'].mean(),inplace=True)
print(df)

    EmpID    Name   Salary       City  Years_of_Experience Department
0     101   Rahul  50000.0  Hyderabad             3.000000         IT
1     102   Priya  60000.0  Bangalore             5.000000         HR
2     103    Amit  55000.0    Chennai             4.000000    Finance
3     104   Sneha  70000.0     Mumbai             7.000000         IT
4     105   Kiran  65000.0  Hyderabad             2.000000  Marketing
5     106  Anjali  65000.0   5.142857             6.000000         HR
6     107  Vikram  80000.0       Pune             5.142857    Finance
7     108    Neha  72000.0      Delhi             8.000000         IT
8     109   Rahul  50000.0  Hyderabad             3.000000         IT
9     110   Arjun  58000.0    Chennai             4.000000    Finance
10    111   Pooja  62000.0  Bangalore             5.000000         HR
11    112   Kiran  65000.0  Hyderabad             2.000000  Marketing
12    113   Manoj  75000.0     Mumbai             9.000000         IT
13    114   Divya  68000.0       Pune             6.000000  Marketing
14    115    Neha  72000.0      Delhi             8.000000         IT

In [31]:
#Rename column to lowercase
df.columns=df.columns.str.lower()
print(df)

    empid    name   salary       city  years_of_experience department
0     101   Rahul  50000.0  Hyderabad             3.000000         IT
1     102   Priya  60000.0  Bangalore             5.000000         HR
2     103    Amit  55000.0    Chennai             4.000000    Finance
3     104   Sneha  70000.0     Mumbai             7.000000         IT
4     105   Kiran  65000.0  Hyderabad             2.000000  Marketing
5     106  Anjali  65000.0   5.142857             6.000000         HR
6     107  Vikram  80000.0       Pune             5.142857    Finance
7     108    Neha  72000.0      Delhi             8.000000         IT
8     109   Rahul  50000.0  Hyderabad             3.000000         IT
9     110   Arjun  58000.0    Chennai             4.000000    Finance
10    111   Pooja  62000.0  Bangalore             5.000000         HR
11    112   Kiran  65000.0  Hyderabad             2.000000  Marketing
12    113   Manoj  75000.0     Mumbai             9.000000         IT
13    114   Divya  68000.0       Pune             6.000000  Marketing
14    115    Neha  72000.0      Delhi             8.000000         IT

In [47]:
#Remove duplicates
dup=df.drop_duplicates(subset="name")
print(dup)

    empid    name   salary       city  years_of_experience department
0     101   Rahul  50000.0  Hyderabad             3.000000         IT
1     102   Priya  60000.0  Bangalore             5.000000         HR
2     103    Amit  55000.0    Chennai             4.000000    Finance
3     104   Sneha  70000.0     Mumbai             7.000000         IT
4     105   Kiran  65000.0  Hyderabad             2.000000  Marketing
5     106  Anjali  65000.0   5.142857             6.000000         HR
6     107  Vikram  80000.0       Pune             5.142857    Finance
7     108    Neha  72000.0      Delhi             8.000000         IT
9     110   Arjun  58000.0    Chennai             4.000000    Finance
10    111   Pooja  62000.0  Bangalore             5.000000         HR
12    113   Manoj  75000.0     Mumbai             9.000000         IT
13    114   Divya  68000.0       Pune             6.000000  Marketing

In [44]:
#Display all exployees from the it department
df[df["department"]=="IT"]

    empid   name   salary       city  years_of_experience department
0     101  Rahul  50000.0  Hyderabad                  3.0         IT
3     104  Sneha  70000.0     Mumbai                  7.0         IT
7     108   Neha  72000.0      Delhi                  8.0         IT
8     109  Rahul  50000.0  Hyderabad                  3.0         IT
12    113  Manoj  75000.0     Mumbai                  9.0         IT
14    115   Neha  72000.0      Delhi                  8.0         IT

In [46]:
#Find employees whose salary is greater than 70000
df[df["salary"]>70000]

    empid    name   salary    city  years_of_experience department
6     107  Vikram  80000.0    Pune             5.142857    Finance
7     108    Neha  72000.0   Delhi             8.000000         IT
12    113   Manoj  75000.0  Mumbai             9.000000         IT
14    115    Neha  72000.0   Delhi             8.000000         IT

In [48]:
#Show employees working in hyderabad
df[df['city']=='Hyderabad']

    empid   name   salary       city  years_of_experience department
0     101  Rahul  50000.0  Hyderabad                  3.0         IT
4     105  Kiran  65000.0  Hyderabad                  2.0  Marketing
8     109  Rahul  50000.0  Hyderabad                  3.0         IT
11    112  Kiran  65000.0  Hyderabad                  2.0  Marketing

In [49]:
#Find experience with more than 5yers of experience
df[df['years_of_experience']>5.0]

    empid    name   salary      city  years_of_experience department
3     104   Sneha  70000.0    Mumbai             7.000000         IT
5     106  Anjali  65000.0  5.142857             6.000000         HR
6     107  Vikram  80000.0      Pune             5.142857    Finance
7     108    Neha  72000.0     Delhi             8.000000         IT
12    113   Manoj  75000.0    Mumbai             9.000000         IT
13    114   Divya  68000.0      Pune             6.000000  Marketing
14    115    Neha  72000.0     Delhi             8.000000         IT

In [61]:
#Show employees who belong to either IT or Finance department
df[(df['department'].isin(['IT','Finance']))]

    empid    name   salary       city  years_of_experience department
0     101   Rahul  50000.0  Hyderabad             3.000000         IT
2     103    Amit  55000.0    Chennai             4.000000    Finance
3     104   Sneha  70000.0     Mumbai             7.000000         IT
6     107  Vikram  80000.0       Pune             5.142857    Finance
7     108    Neha  72000.0      Delhi             8.000000         IT
8     109   Rahul  50000.0  Hyderabad             3.000000         IT
9     110   Arjun  58000.0    Chennai             4.000000    Finance
12    113   Manoj  75000.0     Mumbai             9.000000         IT
14    115    Neha  72000.0      Delhi             8.000000         IT

In [63]:
#Display employees whose salary lies between 60000 and 80000
df[df["salary"].between(60000,80000)]

    empid    name   salary       city  years_of_experience department
1     102   Priya  60000.0  Bangalore             5.000000         HR
3     104   Sneha  70000.0     Mumbai             7.000000         IT
4     105   Kiran  65000.0  Hyderabad             2.000000  Marketing
5     106  Anjali  65000.0   5.142857             6.000000         HR
6     107  Vikram  80000.0       Pune             5.142857    Finance
7     108    Neha  72000.0      Delhi             8.000000         IT
10    111   Pooja  62000.0  Bangalore             5.000000         HR
11    112   Kiran  65000.0  Hyderabad             2.000000  Marketing
12    113   Manoj  75000.0     Mumbai             9.000000         IT
13    114   Divya  68000.0       Pune             6.000000  Marketing
14    115    Neha  72000.0      Delhi             8.000000         IT

In [64]:
#Find the number of employees in each department
df.groupby("department")["name"].count()

department
Finance      3
HR           3
IT           6
Marketing    3
Name: name, dtype: int64

In [65]:
#Calculate total salary paid by each department
df.groupby("department")["salary"].sum()

department
Finance      193000.0
HR           187000.0
IT           389000.0
Marketing    198000.0
Name: salary, dtype: float64

In [67]:
#Find the average salary of employees in each city
df.groupby("city")["salary"].mean()

city
5.142857     65000.0
Bangalore    61000.0
Chennai      56500.0
Delhi        72000.0
Hyderabad    57500.0
Mumbai       72500.0
Pune         74000.0
Name: salary, dtype: float64

In [72]:
#Using a single aggregation,calculate for each department:
#avg,max,min,total salary
df.groupby("department")["salary"].agg(["mean","max","min","sum"])

                    mean      max      min       sum
department
Finance     64333.333333  80000.0  55000.0  193000.0
HR          62333.333333  65000.0  60000.0  187000.0
IT          64833.333333  75000.0  50000.0  389000.0
Marketing   66000.000000  68000.0  65000.0  198000.0

In [73]:
# Create a pivot table showing average salary by department
pd.pivot_table(df,values="salary",index="department",aggfunc="mean")

                  salary
department
Finance     64333.333333
HR          62333.333333
IT          64833.333333
Marketing   66000.000000